# Generated by Django 5.1.5 on 2025-04-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('inventory manager', 'Inventory Manager'), ('procurement officer', 'Procurement Officer'), ('admin', 'Admin')], default='teacher', max_length=20),
        ),
    ]
